# Generated by Django 5.0.2 on 2024-04-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleclass',
            name='author',
        ),
    ]
