# Generated by Django 5.0.2 on 2024-05-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_remove_articleclass_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='editor',
            field=models.BooleanField(default=False),
        ),
    ]
