# Generated by Django 5.0.2 on 2024-06-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_articleclass_total_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleclass',
            name='ratings',
        ),
    ]
