# Generated by Django 5.0.2 on 2024-06-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_remove_articleclass_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleclass',
            name='total_review',
        ),
    ]
