# Generated by Django 5.0.2 on 2024-06-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_remove_articleclass_total_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleclass',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
